#
# CI jobs for https://github.com/maropu/duckdb_extension_example
#
name: maropu/duckdb_extension_example Extension Distribution
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb_extension_example:
    name: A simple table function example in DuckDB
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      extension_name: sayhello
      override_repository: maropu/duckdb_extension_example
      override_ref: master
      duckdb_version: v1.1.3
      override_ci_tools_repository: ${{ github.repository }}
      ci_tools_version: ${{ github.sha }}
      extra_toolchains: ''
